### ISSUE TITLE
Can't run chapter 5 ManualAdviceDemo

### ISSUE THREAD

**Issue by tehnodev** [Apress/pro-spring-6#3]
Compiling is ok, but when i run from chapter05 folder
```
java -cp .\target\classes\ com.apress.prospring6.five.manual.ManualAdviceDemo
```
i get
```
Error: Unable to initialize main class com.apress.prospring6.five.manual.ManualAdviceDemo
Caused by: java.lang.NoClassDefFoundError: org/aopalliance/aop/Advice
```
What is wrong?

**Comment by iuliana** [comment]
Hello @tehnodev, 

How are you trying to run the class? 

`java -cp` is not going to do it, since the `org/aopalliance/aop/Advice` is not on the classpath, unless you omitted some part of your command in this comment. (And you would have to have the entire Spring framework dependencies too)

The recommendation in the book is to use Gradle or Maven to compile the project and use IntelliJ IDEA to run individual classes manually. The `chapter05` has multiple main classes, and thus using Maven or Gradle to run individual classes using execution plugins is not possible. 

Running manually in an editor is also practical, because you can add breakpoints and inspect the objects. 

![Screenshot 2023-11-05 at 22 05 00](https://github.com/Apress/pro-spring-6/assets/2484724/5d010dcb-f0b2-4ee4-a3ce-1b8e994bacc4)

Hope this clears it up for you!

Cheers, 
Iuliana Cosmina

**Comment by tehnodev** [comment]
How can i run examples from command line? Can you show the minimal example from which i can expand to other examples? Is org/aopalliance/aop/Advice built in into IntelliJ? I looked at parent pom and chapter specific pom and i can't find where this dependency is defined.

**Comment by iuliana** [comment]
Hello @tehnodev, 

Why do you want to run the examples from the command line? To run the examples from the command line, you would need to add the entire classpath in the command line. Since you are using Spring, this means all Spring dependencies. You would need to have all the dependencies in the this picture (except test dependencies).

![Screenshot 2023-11-06 at 08 24 59](https://github.com/Apress/pro-spring-6/assets/2484724/b9ca02c9-71ac-4943-adb9-b9658f471aae)

This screenshot is from IntelliJ the Maven view, btw.

IntelliJ IDEA builds the classpath based on the build tool used, so you don't have to do crazy things such as building the classpath manually. 

The `pom.xml` of module `chapter05` does not have `spring-aop`in it, because it is a transitive dependency of `spring-context` as shown in the previous screen shot. 

`org.aopalliance.aop.Advice` is part of the of the `spring-aop` jar. 

![Screenshot 2023-11-06 at 08 29 33](https://github.com/Apress/pro-spring-6/assets/2484724/47f7f5a3-45a0-41ff-b550-6207534743a6)

This screenshot is also from IntelliJ IDEA, I just focused on the `SimpleBeforeAdvice`  class and traversed its inheritance tree until I've found the `Advice` interface and then focused on it an IntelliJ IDEA showed me where it is coming from in the project view.

I think you might have bit more than you can chew with this book, because unfortunately you only seem to have a very small grasp of Mavenand IntelliJ IDEA. Java projects that involve frameworks such a Spring cannot be run without a build tool. So maybe, experiment with Maven a little and get used to the IntelliJ IDEA editor to use it proficiently before jumping into Spring. Or follow the building and running instructions as explained in the book. 

Not sure what is the reason why you want to run classes manually using `java` directly, that is not feasible for projects with a lot of dependencies.  Most companies have stuffy projects like these, and they definitely use a build tool, so maybe getting yourself familiar with one is not such a bad thing. 

Good luck!
Iuliana

**Comment by tehnodev** [comment]
Ok, i got it. I thought that mvn compile puts everything in target directory, not only my compiled java files but also project dependencies. I should better know maven. Thank you for help. You wrote excellent book!

**Comment by iuliana** [comment]
> not feasible for projects with a lot of dependencies. Most companies have stuffy projects like these, and they definitely use a build tool, so maybe getting yourself familiar with one is not such a bad thing.

Thank you @tehnodev !  I hope you don't get to hung up on these little things and manage to enjoy it and learn from it.
